module StandardId
  module Providers
    # Namespace for the Railties generated by {Providers.plugin_railtie}.
    module Railties; end

    class << self
      # Define the Railtie that registers a provider plugin with StandardId.
      #
      # Replaces the hand-written `lib/standard_id/<name>/railtie.rb` every
      # provider plugin used to carry. Call it from the plugin's entry file,
      # after the provider class is required:
      #
      #   # lib/standard_id/github.rb
      #   require "standard_id"
      #   require "standard_id/github/providers/github"
      #
      #   StandardId::Providers.plugin_railtie(:github, "StandardId::Providers::GitHub")
      #
      # The generated Railtie (`StandardId::Providers::Railties::<Name>`)
      # registers the provider from `config.after_initialize`, once the host's
      # configuration is complete. Its config fields are declared earlier, before
      # `config/initializers` run, by StandardId's own engine initializer — the
      # plugin has nothing further to do for that.
      #
      # Outside Rails (no `Rails::Railtie`) nothing is defined and nil is
      # returned, so the entry file needs no `if defined?(Rails)` guard.
      #
      # Idempotent: calling it again for the same name returns the existing
      # Railtie rather than defining a second one (which would register twice).
      #
      # @param name [Symbol, String] Provider identifier, as passed to
      #   ProviderRegistry.register (e.g. :google)
      # @param provider_class [Class, String] The provider class, or its name.
      #   A String is constantized when the Railtie runs, so the entry file may
      #   call this before the class is loaded.
      # @return [Class, nil] the Railtie class
      def plugin_railtie(name, provider_class)
        return nil unless defined?(::Rails::Railtie)

        const_name = name.to_s.camelize
        if Railties.const_defined?(const_name, false)
          return Railties.const_get(const_name, false)
        end

        provider_name = name.to_sym
        railtie = Class.new(::Rails::Railtie)
        Railties.const_set(const_name, railtie)

        railtie.config.after_initialize do
          klass = provider_class.is_a?(String) ? provider_class.constantize : provider_class
          StandardId::ProviderRegistry.register(provider_name, klass)
          Rails.logger&.debug("[StandardId] registered provider #{provider_name}")
        end

        railtie
      end
    end
  end
end
